ci: update

diff --git a/.github/workflows/commitlint.yaml b/.github/workflows/commitlint.yaml
--- a/.github/workflows/commitlint.yaml
+++ b/.github/workflows/commitlint.yaml
@@ -35,19 +35,38 @@ jobs:
         run: |
           echo "Running commitlint..."
           npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose | tee commitlint.log
-          cat commitlint.log
+          if [ $? -eq 0 ]; then
+            echo "COMMITLINT_RESULT=success" >> $GITHUB_ENV
+          else
+            echo "COMMITLINT_RESULT=failure" >> $GITHUB_ENV
+          fi
 
-  create_pr_comment:
-    runs-on: ubuntu-latest
-    needs: commitlint
-    if: always() && github.event_name == 'pull_request'
-    steps:
+      - name: Validate commits with Commitlint
+        id: commitlint
+        run: |
+          echo "Running commitlint..."
+          npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose | tee commitlint.log
+          if [ $? -eq 0 ]; then
+            echo "COMMITLINT_RESULT=success" >> $GITHUB_ENV
+          else
+            echo "COMMITLINT_RESULT=failure" >> $GITHUB_ENV
+          fi
+
+      - name: Read commitlint result
+        id: read_commitlint_result
+        run: |
+          RESULT=$(cat commitlint.log)
+          echo "RESULT<<EOF" >> $GITHUB_ENV
+          echo "$RESULT" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
       - name: Create PR comment
         uses: actions/github-script@v7
+        if: always() # Executa sempre, mas o conteúdo do comentário depende do resultado do commitlint
         with:
           script: |
-            const result = process.env.RESULT;
             const commitlintResult = process.env.COMMITLINT_RESULT;
+            const result = process.env.RESULT;
             const commentBody = commitlintResult === 'success'
               ? '🎉 Commitlint check passed! All commits follow the required standards. 🚀'
               : `❌ Commitlint check failed ❌\n\n📝 Result:\n\n${result}\n\nSome of your commits do not adhere to the required standards. Please review and adjust them to follow the commit message guidelines. 🛠️🔍`;
